version: "3.8"

services:
  idea-generator:
    container_name: generator_golang
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ideas
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
            - .:/usr/src/app
    depends_on:
      - db
  db:
    container_name: db_container
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ideas
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db:
